org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

mod_version=0.1.0
group=me.caitlyn
java_version=21

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_form_version=1.21.1-20240808.144430
neoforge_version=21.1.235
neoforge_loader_version_range=[4,)
parchment_minecraft=1.21
parchment_version=2024.11.10

mod_id=opensockets
mod_name=OpenSockets
mod_author=Caitlyn
license=MIT
description=Listening TCP sockets for OpenComputers: Rebooted computers.

opencomputers_version=1.9.4-2
opencomputers_api_version=1.9.4-2
opencomputers_scala_version=3.3.3-build-15
