org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

mod_version=0.1.0
group=me.caitlyn
mod_id=opensockets
mod_name=OpenSockets
mod_author=Caitlyn
description=Listening TCP sockets for original OpenComputers on Minecraft 1.12.2.

minecraft_version=1.12.2
minecraft_mappings=39-1.12
forge_version=14.23.5.2860
opencomputers_version=MC1.12.2-1.7.7+5413028
opencomputers_dependency=curse.maven:opencomputers-223008:3966135
